name: markdown
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  process_labels:
    runs-on: ubuntu-latest
    steps:
    - name: run code
      run: |
        echo "origin/${{ github.event.pull_request.base.ref }}"
